[auth]
api_key = "" #public key
api_key_auth = "" #private key

[notify]
nootification_on_desktop = false #true or false
enabled = true #true or false
symbols = ["BTC-USDT","BIP-USDT"]
timeout = 30 #seconds
time = 0.5 #minutes

[scallping]
nootification_on_desktop = false #true or false
enabled = false #true or false
symbols = ["BTC-USDT"] #more pairs can be cause of errors
percent = 0.001
percent_to_play = 80
save_percent = 2
strategy = "last" #last(recomemded) or normal

[triangle]
#WARNING THIS IS TEST FUNCTION! 
#STRATEGY CAN WORK VERY BAD
nootification_on_desktop = false #true or false
enabled = true #true or false
ordering = false
timeout = 5 #minutes 
symbol = "USDT"
min_percent = 6
percent_to_play = 80
